backend:
  name: git-gateway
  branch: master
media_folder: "src/images"
public_folder: "/images"
logo_url: "https://floriade.co.nz/icons/floriade-icon-round-512.png"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - label: "Blog"
    name: "blog"
    label_singular: "Blog Post"
    folder: "src/blog"
    create: true
    delete: false
    slug: "{{slug}}"
    media_folder: '/{{media_folder}}/blog'
    public_folder: '{{public_folder}}/blog'
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD MMM YYYY", time_format: false}
      - {label: "Header Image", name: "header_image", widget: "image", choose_url: false, required: false}
      - {label: "Post Body", name: "body", widget: "markdown", buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'quote', 'bulleted-list', 'numbered-list'], editor_components: ['image'], modes: ['rich_text']}
  - label: "Pages"
    name: "pages"
    label_singular: "Page"
    folder: "src/pages"
    create: true
    delete: false
    filter: {field: "page_type", value: "builder"}
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Page Type", name: "page_type", widget: "hidden", default: "builder"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Header Title", name: "header_title", widget: "string", required: false}
      - {label: "Header Image", name: "header_image", widget: "image", choose_url: false, required: false}
      - label: "Menu"
        name: "eleventyNavigation"
        collapsed: true
        widget: "object"
        fields:
          - { label: "Name", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - label: "Page Sections"
        name: "page_sections"
        label_singular: "Section"
        widget: "list"
        types:
          - label: "Text"
            name: "text-section"
            widget: "object"
            summary: '{{fields.text}}'
            fields:
              - {label: "Text", name: "text", widget: "markdown", buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'quote', 'bulleted-list', 'numbered-list'], editor_components: [], modes: ['rich_text'], minimal: true}
              - {label: "Alternate Background Colour", name: "alternate_background_color", widget: "boolean", required: false}
              - label: "Align Text"
                name: "align"
                widget: "select"
                required: false
                default: "Left"
                options: ["Left", "Center", "Right"]
              - label: "Button"
                name: "button"
                collapsed: true
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string", required: false }
                  - { label: "Link", name: "link", widget: "string", required: false }
                  - { label: "Open in new Tab/Window", name: "new_page", widget: "boolean", required: false }
          - label: "Image"
            name: "image-section"
            widget: "object"
            summary: '{{fields.image}}'
            fields:
              - {label: "Image", name: "image", widget: "image", choose_url: false}
              - {label: "Alt Text", name: "alt-text", widget: "string" }
              - {label: "Title", name: "caption", widget: "string", required: false }
              - {label: "Photographer", name: "photographer", widget: "relation", collection: "lists", file: "photographers", value_field: "name", search_fields: ["name"], required: false}
              - {label: "Alternate Background Colour", name: "alternate_background_color", widget: "boolean", required: false}
          - label: "Contact Form"
            name: "contact-form-section"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string", required: false, hint: "eg. Contact Us or Send us a Message"}
              - {label: "Message placeholder", name: "message", widget: "string", required: false, hint: "eg. How can we help you?"}
              - {label: "Email Subject", name: "email_subject", widget: "string", required: false, hint: "eg. Flowers Enquiry"}
              - {label: "Email Reply Heading", name: "email_heading", widget: "string", required: false, hint: "eg. Thankyou for contacting Floriade"}
              - {label: "Alternate Background Colour", name: "alternate_background_color", widget: "boolean", required: false}
          - label: "Instagram Gallery"
            name: "instagram-gallery-section"
            widget: "object"
            fields:
              - {label: "Dummy", name: "dummy", widget: "hidden", required: false}
  - label: "Special Pages"
    name: "special-pages"
    label_singular: "Page"
    folder: "src/pages"
    delete: false
    filter: {field: "page_type", value: "special"}
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Page Type", name: "page_type", widget: "hidden", default: "special"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Header Title", name: "header_title", widget: "string", required: false}
      - {label: "Header Image", name: "header_image", widget: "image", choose_url: false, required: false}
      - label: "Menu"
        name: "eleventyNavigation"
        collapsed: true
        widget: "object"
        fields:
          - { label: "Name", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
  - label: "Shop Hours"
    name: "shop-hours"
    delete: false
    files:
      - label: "Regular Shop Hours"
        name: "regular_shop_hours"
        file: "src/_data/regular_shop_hours.json"
        editor:
          preview: false
        fields:
          - label: "Monday"
            name: "monday"
            widget: "object"
            summary: "{{fields.opens_at}} {{fields.closes_at}} {{fields.closed | ternary('Closed','')}} {{fields.no_delivery | ternary('No Delivery','')}} {{fields.no_pickup | ternary('No Pickup','')}}"
            collapsed: true
            fields:
              - {label: "Opens at", name: "opens_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closes at", name: "closes_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closed", name: "closed", widget: "boolean", required: false}
              - {label: "No Delivery", name: "no_delivery", widget: "boolean", required: false}
              - {label: "No Pickup", name: "no_pickup", widget: "boolean", required: false}
          - label: "Tuesday"
            name: "tuesday"
            widget: "object"
            summary: "{{fields.opens_at}} {{fields.closes_at}} {{fields.closed | ternary('Closed','')}} {{fields.no_delivery | ternary('No Delivery','')}} {{fields.no_pickup | ternary('No Pickup','')}}"
            collapsed: true
            fields:
              - {label: "Opens at", name: "opens_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closes at", name: "closes_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closed", name: "closed", widget: "boolean", required: false}
              - {label: "No Delivery", name: "no_delivery", widget: "boolean", required: false}
              - {label: "No Pickup", name: "no_pickup", widget: "boolean", required: false}
          - label: "Wednesday"
            name: "wednesday"
            widget: "object"
            summary: "{{fields.opens_at}} {{fields.closes_at}} {{fields.closed | ternary('Closed','')}} {{fields.no_delivery | ternary('No Delivery','')}} {{fields.no_pickup | ternary('No Pickup','')}}"
            collapsed: true
            fields:
              - {label: "Opens at", name: "opens_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closes at", name: "closes_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closed", name: "closed", widget: "boolean", required: false}
              - {label: "No Delivery", name: "no_delivery", widget: "boolean", required: false}
              - {label: "No Pickup", name: "no_pickup", widget: "boolean", required: false}
          - label: "Thursday"
            name: "thursday"
            widget: "object"
            summary: "{{fields.opens_at}} {{fields.closes_at}} {{fields.closed | ternary('Closed','')}} {{fields.no_delivery | ternary('No Delivery','')}} {{fields.no_pickup | ternary('No Pickup','')}}"
            collapsed: true
            fields:
              - {label: "Opens at", name: "opens_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closes at", name: "closes_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closed", name: "closed", widget: "boolean", required: false}
              - {label: "No Delivery", name: "no_delivery", widget: "boolean", required: false}
              - {label: "No Pickup", name: "no_pickup", widget: "boolean", required: false}
          - label: "Friday"
            name: "friday"
            widget: "object"
            summary: "{{fields.opens_at}} {{fields.closes_at}} {{fields.closed | ternary('Closed','')}} {{fields.no_delivery | ternary('No Delivery','')}} {{fields.no_pickup | ternary('No Pickup','')}}"
            collapsed: true
            fields:
              - {label: "Opens at", name: "opens_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closes at", name: "closes_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closed", name: "closed", widget: "boolean", required: false}
              - {label: "No Delivery", name: "no_delivery", widget: "boolean", required: false}
              - {label: "No Pickup", name: "no_pickup", widget: "boolean", required: false}
          - label: "Saturday"
            name: "saturday"
            widget: "object"
            summary: "{{fields.opens_at}} {{fields.closes_at}} {{fields.closed | ternary('Closed','')}} {{fields.no_delivery | ternary('No Delivery','')}} {{fields.no_pickup | ternary('No Pickup','')}}"
            collapsed: true
            fields:
              - {label: "Opens at", name: "opens_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closes at", name: "closes_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closed", name: "closed", widget: "boolean", required: false}
              - {label: "No Delivery", name: "no_delivery", widget: "boolean", required: false}
              - {label: "No Pickup", name: "no_pickup", widget: "boolean", required: false}
          - label: "Sunday"
            name: "sunday"
            widget: "object"
            summary: "{{fields.opens_at}} {{fields.closes_at}} {{fields.closed | ternary('Closed','')}} {{fields.no_delivery | ternary('No Delivery','')}} {{fields.no_pickup | ternary('No Pickup','')}}"
            collapsed: true
            fields:
              - {label: "Opens at", name: "opens_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closes at", name: "closes_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closed", name: "closed", widget: "boolean", required: false}
              - {label: "No Delivery", name: "no_delivery", widget: "boolean", required: false}
              - {label: "No Pickup", name: "no_pickup", widget: "boolean", required: false}
      - label: "Special Shop Hours"
        name: "special-shop-hours"
        file: "src/_data/special_shop_hours.json"
        editor:
          preview: false
        fields:
          - label: "Special Shop Hours"
            label_singular: "Date"
            name: "special_shop_hours"
            widget: "list"
            summary: "{{fields.date}} : {{fields.opens_at}} - {{fields.closes_at}} {{fields.closed | ternary('Closed','')}} {{fields.no_delivery | ternary('No Delivery','')}} {{fields.no_pickup | ternary('No Pickup','')}}"
            fields:
              - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD MMM YYYY", time_format: false}
              - {label: "Opens at", name: "opens_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closes at", name: "closes_at", widget: "datetime", format: "HH:mm", date_format: false, time_format: "h:mma", default: "", required: false}
              - {label: "Closed", name: "closed", widget: "boolean", required: false}
              - {label: "No Delivery", name: "no_delivery", widget: "boolean", required: false}
              - {label: "No Pickup", name: "no_pickup", widget: "boolean", required: false}
  - label: "Lists"
    name: "lists"
    delete: false
    files:
      - label: "FAQ"
        name: "faq"
        file: "src/_data/faq.json"
        editor:
          preview: false
        fields:
          - label: "FAQ"
            label_singular: "FAQ"
            name: "faq"
            widget: "list"
            summary: '{{fields.question}}'
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "text"}
      - label: "Photographers"
        name: "photographers"
        file: "src/_data/photographers.json"
        editor:
          preview: false
        fields:
          - label: "Photographers"
            label_singular: "Photographer"
            name: "photographers"
            widget: "list"
            summary: '{{fields.name}}'
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Web Page", name: "webpage", widget: "string"}
      - label: "Reviews"
        name: "reviews"
        file: "src/_data/reviews.json"
        editor:
          preview: false
        fields:
          - label: "Reviews"
            label_singular: "Review"
            name: "reviews"
            widget: "list"
            summary: '{{fields.review}} - {{fields.name}}'
            fields:
              - {label: "Review", name: "review", widget: "text"}
              - {label: "Author", name: "name", widget: "string"}
              - {label: "Wedding", name: "wedding", widget: "boolean"}
  - label: "Globals"
    name: "globals"
    delete: false
    files:
      - label: "Banner Message"
        name: "banner_message"
        file: "src/_data/banner_message.json"
        editor:
          preview: false
        fields:
          - {label: "Message", name: "message", widget: "markdown", buttons: ['bold', 'italic', 'link'], editor_components: [], modes: ['rich_text'], minimal: true}
      - label: "Site Data"
        name: "site_data"
        file: "src/_data/site_data.json"
        editor:
          preview: false
        fields:
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Header Image", name: "header_image", widget: "image"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Suburb", name: "address_locality", widget: "string"}
          - {label: "Region", name: "address_region", widget: "string"}
          - {label: "Postcode", name: "address_postcode", widget: "string"}
      - label: "Theme Settings"
        name: "theme"
        file: "src/_data/tokens.json"
        editor:
          preview: false
        fields:
          - label: "Colors"
            name: "colors"
            widget: "object"
            fields:
              - {label: "Light", name: "colorLight", widget: "color"}
              - {label: "Dark", name: "colorDark", widget: "color"}
              - {label: "Alt", name: "colorAlt", widget: "color"}
              - {label: "Primary", name: "colorPrimary", widget: "color"}
              - {label: "Shade1", name: "colorShade1", widget: "color"}
              - {label: "Shade2", name: "colorShade2", widget: "color"}
              - {label: "Shade3", name: "colorShade3", widget: "color"}
              - {label: "Button", name: "colorButton", widget: "color"}
              - {label: "Autofill", name: "colorAutofill", widget: "color"}
