backend:
  name: git-gateway
  branch: master
media_folder: "src/images"
public_folder: "/images"
logo_url: "https://floriade.co.nz/icons/floriade-icon-round-512.png"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site_data.json"
        editor:
          preview: false
        fields:
          - {label: "SEO Meta Description", name: "description", widget: "text"}
          - {label: "Header Image", name: "header_image", widget: "image"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Suburb", name: "address_locality", widget: "string"}
          - {label: "Region", name: "address_region", widget: "string"}
          - {label: "Postcode", name: "address_postcode", widget: "string"}
      - label: "Theme Settings"
        name: "theme"
        delete: false
        file: "src/_data/tokens.json"
        editor:
          preview: false
        fields:
          - label: "Colors"
            name: "colors"
            widget: "object"
            fields:
              - {label: "Light", name: "colorLight", widget: "color" }
              - {label: "Dark", name: "colorDark", widget: "color" }
              - {label: "Alt", name: "colorAlt", widget: "color" }
              - {label: "Primary", name: "colorPrimary", widget: "color" }
              - {label: "Shade1", name: "colorShade1", widget: "color" }
              - {label: "Shade2", name: "colorShade2", widget: "color" }
              - {label: "Shade3", name: "colorShade3", widget: "color" }
              - {label: "Button", name: "colorButton", widget: "color" }
              - {label: "Autofill", name: "colorAutofill", widget: "color" }
  - label: "Lists"
    name: "lists"
    files:
      - label: "FAQ"
        label_singular: "FAQ"
        name: "faq"
        delete: false
        file: "src/_data/faq.json"
        editor:
          preview: false
        fields:
          - label: "FAQ"
            name: "faq"
            widget: "list"
            summary: '{{fields.question}}'
            fields:
              - {label: "Question", name: "question", widget: "string" }
              - {label: "Answer", name: "answer", widget: "text" }
      - label: "Reviews"
        label_singular: "Review"
        name: "reviews"
        delete: false
        file: "src/_data/reviews.json"
        editor:
          preview: false
        fields:
          - label: "Reviews"
            name: "reviews"
            widget: "list"
            summary: '{{fields.review}} - {{fields.name}}'
            fields:
              - {label: "Review", name: "review", widget: "text" }
              - {label: "Author", name: "name", widget: "string" }
              - {label: "Wedding", name: "wedding", widget: "boolean" }
  - name: "blog"
    label: "Blog"
    label_singular: "Blog Post"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    media_folder: '/{{media_folder}}/blog'
    public_folder: '{{public_folder}}/blog'
    fields:
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", date_format: true, time_format: false }
      - { label: "Header Image", name: "header_mage", widget: "image", required: false }
      - { label: "Post Body", name: "body", widget: "markdown", buttons: ['bold', 'italic', 'link', 'heading-two', 'heading-three', 'quote', 'bulleted-list', 'numbered-list'], editor_components: ['image'], modes: ['rich_text'] }
